added manual kubernetes tls certs to the cert-expire finder
ossobv/vcutil pull request #36
Opened 2024-05-06 13:15 UTC by seppelucas

function list_k8s_cert_expiry_days has been extended to check manual set tls certs and add their expire to the output list.

this is done by checking for an annotation cert-manager provides. when there is no certificate object surrounding the secret we manual need to check the end date with openssl x509

2024-05-07 07:16 UTC, seppelucas commented
it is also a possibility too get all tls secrets and check them this way. without the special function for the cert-manager secrets. 
but i think that for the cert-manager secrets checking the status is faster then using openssl.

2024-05-13 08:16 UTC, wdoekes requested changes
Good improvements.

2024-05-13 08:16 UTC, wdoekes commented on cert-expiry-finder
> +            if [ -z "$annotations" ]; then
Please use `test -z` as the rest of the file uses that.

> [...] i think that for the cert-manager secrets checking the status is faster then using openssl.

Yea. That's perfect. No need to slowly fetch the secrets if the expiry dates are more readily available.

The only thing that bothers me slightly is the duplication of the openssl x509 call here. There is already code that does with some special handling to check multiple certificates (see: enumerate_x509_expiry_seconds and foreach_x509).

Maybe something like:
```bash
echo "$cert" | base64 -d | enumerate_x509_expiry_seconds |
while read -r delta subject; do
    printf '%-7d Kubernetes (NS = %s, CRT = %s, CTX = %s) %s\n' \
                    $delta "$namespace" "$name" "$context" "$subject"
```
(With enumerate_x509_expiry_seconds modified so it takes input from stdin.)

2024-05-14 08:57 UTC, merged

2024-05-14 08:57 UTC, wdoekes commented
:+1: 

Just one:
```
# wc -L cert-expiry-finder
88 cert-expiry-finder
```
But I'll fix that up with a little tweak now.